version: '2'

services:
  web:
    tty: true
    stdin_open: true
    image: mlvk/in-spiritus:0.0.13
    command: bash -c "rm -f tmp/pids/* && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    networks:
      - backend
    volumes:
      - ..:/app/in-spiritus
    depends_on:
      - db
      - redis

  python:
    tty: true
    stdin_open: true
    image: mlvk/in-spiritus-python:0.0.2
    command: tail -f /dev/null
    networks:
      - backend
    volumes:
      - ../tmp/debug/:/var/lib/debug
    depends_on:
      - db
      - redis

  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
     - backend
    volumes:
      - ../tmp/db/pg/db/postgresql/data:/var/lib/postgresql/data
      - ../tmp/db/pg/db/dumps:/var/lib/dumps

  redis:
    image: redis
    networks:
      - backend
    command: redis-server --appendonly yes
    restart: always

  zeus:
    image: mlvk/in-spiritus:0.0.13
    command: bash -c "rm -f /zeus/.zeus.sock && zeus start"
    networks:
      - backend
    volumes:
      - ..:/app/in-spiritus
      - ../tmp/sockets/zeus:/zeus
    environment:
      ZEUSSOCK: /zeus/.zeus.sock
    depends_on:
      - db
      - redis

  # logging:
  #   image: brancusi/remote_syslog:0.0.1
  #   volumes_from:
  #     - web
  #   command: remote_syslog -D -c /app/in-spiritus/config/log_config.yml

networks:
  backend:
