---
- hosts: vm
  roles:
    - swap

- hosts: all
  gather_facts: no
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: postgresql
  roles:
    - postgresql

- hosts: redis
  roles:
    - DavidWittman.redis

- hosts: application
  handlers:
    - include: roles/sidekiq/handlers/main.yml
  roles:
    - base
    - { role: ruby, tags: ruby }
    - vim
    - webserver

- hosts: sidekiq
  handlers:
    - include: roles/unicorn/handlers/main.yml
  roles:
    - base
    - ruby
    - { role: sidekiq, tags: sidekiq }
